.TH FABSCRIPT 1 06/14

.SH NAME
\fBfabscript\fR \- execute a Fabric script

.SH SYNOPSIS
.P
\fBfabscript\fR \fB-n node\fR \fB-i ip\fR \fB-s file\fR
.P

.SH DESCRIPTION
.PP
\fBfabscript\fR executes a Fabric script file. Scripts enable Fabric regression
tests, installation verifications and test harnesses to be developed.

.SH "OPTIONS"
.IP "\fB\-n node\fR" 4
.PD
the ID of the Fabric node to which this script will connect.

.IP "\fB\-i ip\fR" 4
.PD
the IP address of the Fabric node to which this script will connect.

.IP "\fB\-s file\fR" 4
..PD
the script file to execute.

.SH "COPYRIGHT"

(C) Copyright IBM Corp. 2014, 2016. All Rights Reserved.
