#!/bin/bash

# **************************************************************************
# (C) Copyright IBM Corp. 2014
#
# LICENSE: Eclipse Public License v1.0
# http://www.eclipse.org/legal/epl-v10.html
# **************************************************************************

FABRIC_LIBS=$(echo $FABRIC_HOME/lib/db-derby/lib/*.jar | tr ' ' ':')
FABRIC_LIBS=$FABRIC_LIBS:$(echo $FABRIC_HOME/lib/fabric/*.jar | tr ' ' ':')
FABRIC_LIBS=$FABRIC_LIBS:$(echo $FABRIC_HOME/lib/gaiandb/lib/*.jar | tr ' ' ':')
FABRIC_LIBS=$FABRIC_LIBS:$(echo $FABRIC_HOME/lib/oslib/*.jar | tr ' ' ':')

java -Dconfig=$FABRIC_HOME/bin/config/CLI.properties -Dfabric.config=$FABRIC_HOME/osgi/configuration/fabricConfig_default.properties -Djava.util.logging.config.file=$FABRIC_HOME/osgi/configuration/logging.properties -cp $FABRIC_LIBS fabric.tools.DistributedRegistryCLI "${1}"
