#!/bin/bash

# **************************************************************************
# (C) Copyright IBM Corp. 2012
#
# LICENSE: Eclipse Public License v1.0
# http://www.eclipse.org/legal/epl-v10.html
# **************************************************************************

# **************************************************************************
# Invoke the Registry command line tool.
# **************************************************************************

export CLASSPATH=$FABRIC_HOME/lib/db-derby/lib/derbyclient.jar:$FABRIC_HOME/lib/oslib/commons-cli-1.3.1.jar:`ls -1 $FABRIC_HOME/lib/fabric/fabric.admin*.jar`

java fabric.tools.RegistryTool "$@"
